In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
venu = pd.read_csv(r"C:\Users\Admin\Downloads\Swarm_Behaviour.csv")
venu.head()

x1      y1  xVel1  yVel1   xA1   yA1  xS1  yS1   xC1   yC1  ...  \
0   562.05   -0.62 -10.70  -4.33  0.00  0.00  0.0  0.0  0.00  0.00  ...   
1   175.66  -57.09   2.31  -2.67  0.00  0.00  0.0  0.0  0.00  0.00  ...   
2   200.16 -320.07   4.01  -6.37  0.00  0.00  0.0  0.0  0.18 -0.26  ...   
3   316.99 -906.84   0.85   9.17 -0.17  1.03  0.0  0.0  0.00  0.00  ...   
4  1277.68  908.54  -2.02   8.23 -1.00  1.00  0.0  0.0  0.00  0.00  ...   

   yVel200  xA200  yA200  xS200  yS200  xC200  yC200  nAC200  nS200  \
0   -15.15   0.00   0.00   0.00   0.00   0.00    0.0      28      0   
1    -3.48   0.00   0.00   0.00   0.00   0.00    0.0       4      0   
2    -9.38   0.00   0.00   0.00   0.00  -0.11   -0.3      15      1   
3    10.39  -0.26   1.01   0.00   0.00   0.00    0.0      16      0   
4    13.91  -1.00   0.00   3.21  15.67   0.00    0.0      12      0   

   Swarm_Behaviour  
0              0.0  
1              0.0  
2              0.0  
3              0.0  
4              0.0  

[5 rows x 2401 columns]

In [3]:
venu.tail()

x1      y1  xVel1  yVel1   xA1   yA1  xS1  yS1   xC1   yC1  ...  \
23304  -225.85  128.99  12.19  -7.56 -1.00  0.00  0.0  0.0  0.00  0.00  ...   
23305 -1352.02 -233.03  -0.86  -4.37 -0.07 -0.55  0.0  0.0  0.28  0.02  ...   
23306 -1360.61 -778.11  -2.89  -1.17  0.00  0.00  0.0  0.0  0.00  0.00  ...   
23307   987.11  615.69  -5.61  -2.92 -1.00 -1.00  0.0  0.0  0.00  0.00  ...   
23308   938.12 -924.87  11.18   2.85  0.10 -0.02  0.0  0.0  0.06  0.31  ...   

       yVel200  xA200  yA200  xS200  yS200  xC200  yC200  nAC200  nS200  \
23304    -5.06  -1.00  -1.00  -3.99   0.21   0.00   0.00      17      1   
23305   -12.41  -0.15  -0.70   0.00   0.00   0.02   0.07      69      1   
23306   -14.78   0.00   0.00   0.00   0.00   0.00   0.00      20      1   
23307     9.78  -1.00  -1.00   0.00   0.00   0.00   0.00      29      0   
23308    -2.90  -0.13  -0.29   1.31   0.38   0.00   0.00       2      1   

       Swarm_Behaviour  
23304              0.0  
23305              0.0  
23306              0.0  
23307              0.0  
23308              0.0  

[5 rows x 2401 columns]

In [4]:
venu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23309 entries, 0 to 23308
Columns: 2401 entries, x1 to Swarm_Behaviour
dtypes: float64(2001), int64(400)
memory usage: 427.0 MB


In [5]:
venu.isnull().sum()

x1                 0
y1                 0
xVel1              0
yVel1              0
xA1                0
                  ..
xC200              0
yC200              0
nAC200             0
nS200              0
Swarm_Behaviour    0
Length: 2401, dtype: int64

In [6]:
x= venu.iloc[:,:-1].values  
y= venu.iloc[:,-1].values  

In [7]:
x
y

array([0., 0., 0., ..., 0., 0., 0.])

In [8]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=44)  

In [9]:
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test)  

In [10]:
from sklearn.linear_model import LogisticRegression  
classifier = LogisticRegression()

In [15]:
classifier.fit(x_train , y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [14]:
y_pred= classifier.predict(x_test)  

In [16]:
y_pred

array([0., 1., 0., ..., 0., 1., 0.])

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(y_test,y_pred)

array([[3462,  351],
       [ 364, 1651]], dtype=int64)

In [18]:
accuracy_score(y_test,y_pred)

0.8773164035689773

In [19]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.90      0.91      0.91      3813
         1.0       0.82      0.82      0.82      2015

    accuracy                           0.88      5828
   macro avg       0.86      0.86      0.86      5828
weighted avg       0.88      0.88      0.88      5828



In [20]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()

In [21]:
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)

In [29]:
classifier.predict_log_proba(x_test)

array([[-1865.08297949,     0.        ],
       [-1684.59211801,     0.        ],
       [ -362.90306607,     0.        ],
       ...,
       [ -278.7922786 ,     0.        ],
       [-1406.11012447,     0.        ],
       [ -255.49987073,     0.        ]])

In [30]:
print(confusion_matrix(y_test,y_pred))
print('accuracy:',accuracy_score(y_test,y_pred))

[[ 732 3081]
 [  53 1962]]
accuracy: 0.4622512010981469


In [31]:
from sklearn.neighbors import KNeighborsClassifier
k = KNeighborsClassifier()

In [32]:
k.fit(x_train , y_train)
k_pred = k.predict(x_test)

In [25]:
print(classification_report(y_test , k_pred))

              precision    recall  f1-score   support

         0.0       0.91      0.92      0.91      3813
         1.0       0.84      0.82      0.83      2015

    accuracy                           0.89      5828
   macro avg       0.88      0.87      0.87      5828
weighted avg       0.89      0.89      0.89      5828



In [26]:
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier()

In [27]:
DT.fit(x_train , y_train)
DT_pred = DT.predict(x_test)

In [28]:
print(classification_report(y_test , DT_pred))

              precision    recall  f1-score   support

         0.0       0.89      0.91      0.90      3813
         1.0       0.82      0.78      0.80      2015

    accuracy                           0.87      5828
   macro avg       0.86      0.85      0.85      5828
weighted avg       0.87      0.87      0.87      5828



In [33]:
yes = DecisionTreeClassifier(criterion = 'entropy')
yes.fit(x_train , y_train)
y_predd = yes.predict(x_test)

In [34]:
print(classification_report(y_test , y_predd))

              precision    recall  f1-score   support

         0.0       0.89      0.90      0.90      3813
         1.0       0.81      0.78      0.80      2015

    accuracy                           0.86      5828
   macro avg       0.85      0.84      0.85      5828
weighted avg       0.86      0.86      0.86      5828

